### ISSUE TITLE
Crash when sending to gadgetbridge (again)

### ISSUE THREAD

**Issue by kosmoz** [breezy-weather/breezy-weather#1072]
### Steps to reproduce

See https://github.com/breezy-weather/breezy-weather/issues/951 for details

### Expected behavior

No crash

### Actual behavior

Crash

### Weather source used

GeosphereAT for air quality

### Breezy Weather version

5.2.3

### Android version

13

### Device

Fairphone 4

### Other details

Stack trace: 
```
05-25 11:22:33.033 29999  7988 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
05-25 11:22:33.033 29999  7988 E AndroidRuntime: Process: org.breezyweather, PID: 29999
05-25 11:22:33.033 29999  7988 E AndroidRuntime: D2.e: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | kotlinx.serialization.json.internal.l: Unexpected special floating-point value NaN. By default, non-finite floating point values are prohibited because they do not conform JSON specification. It is possible to deserialize them using 'JsonBuilder.allowSpecialFloatingPointValues = true'
05-25 11:22:33.033 29999  7988 E AndroidRuntime: Current output: .....":1716698460,"moonPhase":215,"airQuality":{"aqi":35,"co":NaN
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at O1.e.c(SourceFile:5)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.observers.c.onError(Unknown Source:13)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.d.onError(Unknown Source:37)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.d.onComplete(Unknown Source:36)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.m.checkTerminated(SourceFile:61)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.m.drainNormal(Unknown Source:30)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.m.run(Unknown Source:8)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.p.run(Unknown Source:13)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.p.call(Unknown Source:0)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: Caused by: kotlinx.serialization.json.internal.l: Unexpected special floating-point value NaN. By default, non-finite floating point values are prohibited because they do not conform JSON specification. It is possible to deserialize them using 'JsonBuilder.allowSpecialFloatingPointValues = true'
05-25 11:22:33.033 29999  7988 E AndroidRuntime: Current output: .....":1716698460,"moonPhase":215,"airQuality":{"aqi":35,"co":NaN
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.o.b(SourceFile:30)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.m(SourceFile:57)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.internal.z.serialize(SourceFile:12)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.l(SourceFile:14)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.x(SourceFile:24)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.r(SourceFile:19)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeAirQuality.write$Self$app_basicRelease(SourceFile:36)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeAirQuality$$serializer.serialize(SourceFile:2)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeAirQuality$$serializer.serialize(SourceFile:1)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.l(SourceFile:14)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.x(SourceFile:24)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.r(SourceFile:19)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeDailyForecast.write$Self$app_basicRelease(SourceFile:270)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeDailyForecast$$serializer.serialize(SourceFile:2)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeDailyForecast$$serializer.serialize(SourceFile:1)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.l(SourceFile:14)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.y(SourceFile:14)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.internal.n.serialize(SourceFile:45)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.l(SourceFile:14)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.x(SourceFile:24)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.r(SourceFile:19)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeData.write$Self$app_basicRelease(SourceFile:452)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeData$$serializer.serialize(SourceFile:2)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.gadgetbridge.json.GadgetbridgeData$$serializer.serialize(SourceFile:1)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.B.l(SourceFile:14)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at kotlinx.serialization.json.internal.o.k(SourceFile:52)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at q3.c.b(SourceFile:55)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at org.breezyweather.sources.p.b(SourceFile:345)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at G0.o.run(SourceFile:140)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at Z3.a.run(SourceFile:13)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.d.onComplete(Unknown Source:7)
05-25 11:22:33.033 29999  7988 E AndroidRuntime: 	... 10 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by kosmoz** [comment]
I think I found the source of the `NaN` values. Will open a PR :slightly_smiling_face:
