### ISSUE TITLE
App Crashes after a fresh install with v4.1.0-beta

### ISSUE THREAD

**Issue by GrassBlock1** [breezy-weather/breezy-weather#126]
### Steps to reproduce

1. Install release on Github
2. open the app
3. got a splash screen and crashed
4. grant permissons, reopen the app
5. same as 3.

### Expected behavior

app should run normally and displayer weather info.

### Actual behavior

It just show a splash and crashed.

### Weather provider used

none

### Breezy Weather version

4.1.0-beta

### Android version

Android 10 with EMUI 10.1

### Device

Honor 9X

### Other details

logs grabbed with adb: https://pastebin.eldshort.de/xtZ5SagHdK72Xg9Y3dv6E

I try to launch the widget activity and it works.

I have tried with arm64 and universal package, but neither works for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Decoded stacktrace:
```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.ArrayStoreException: destination of type java.util.ArrayList is not an array
        at io.reactivex.rxjava3.internal.functions.Functions$EmptyConsumer.void io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(java.lang.Throwable)(SourceFile:12)
                                                                    void io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(java.lang.Object)
                                                                    void accept$bridge(java.lang.Object)
        at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(Unknown Source:13)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(Unknown Source:37)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(Unknown Source:25)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(Unknown Source:47)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(Unknown Source:8)
        at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.void io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run()(SourceFile:9)
                                                                               void run$bridge()
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Caused by: java.lang.ArrayStoreException: destination of type java.util.ArrayList is not an array
        at java.lang.System.arraycopy(Native Method)
        at org.breezyweather.main.MainActivityViewModel.java.lang.String[] org.breezyweather.location.LocationHelper.getPermissions(android.content.Context)(SourceFile:123)
                                                 java.util.List org.breezyweather.main.MainActivityRepository.getLocatePermissionList(android.content.Context)
                                                 void updateWithUpdatingChecking(boolean,boolean)
        at org.breezyweather.main.MainActivityViewModel.void checkToUpdateCurrentLocation()(SourceFile:56)
        at org.breezyweather.main.MainActivityViewModel.void setCurrentLocation(org.breezyweather.common.basic.models.Location)(Unknown Source:21)
        at org.breezyweather.main.MainActivityViewModel.void updateInnerData(java.util.List)(Unknown Source:79)
        at org.breezyweather.main.MainActivityViewModel$init$2.void org.breezyweather.main.MainActivityViewModel.access$updateInnerData(org.breezyweather.main.MainActivityViewModel,java.util.List)(SourceFile:4)
                                                        void invoke(java.util.List,boolean)
        at org.breezyweather.main.MainActivityViewModel$init$2.java.lang.Object invoke(java.lang.Object,java.lang.Object)(SourceFile:1)
        at androidx.compose.animation.core.VectorizedAnimationSpecKt$createSpringAnimations$1.void org.breezyweather.common.utils.helpers.AsyncHelper$runOnExecutor$2.accept(org.breezyweather.common.utils.helpers.AsyncHelper$Data)(SourceFile:24)
                                                                                       void org.breezyweather.common.utils.helpers.AsyncHelper$runOnExecutor$2.accept$bridge(org.breezyweather.common.utils.helpers.AsyncHelper$Data)
        at androidx.compose.animation.core.VectorizedAnimationSpecKt$createSpringAnimations$1.void org.breezyweather.common.utils.helpers.AsyncHelper$runOnExecutor$2.accept(java.lang.Object)(SourceFile:15)
                                                                                       void org.breezyweather.common.utils.helpers.AsyncHelper$runOnExecutor$2.accept$bridge(java.lang.Object)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(Unknown Source:7)
        ... 10 more
```

Faulty function to investigate: https://github.com/breezy-weather/breezy-weather/blob/v4.1.0-beta/app/src/main/java/org/breezyweather/location/LocationHelper.kt#L140
