### ISSUE TITLE
[main branch] Crash when displaying nowcasting chart

### ISSUE THREAD

**Issue by ccyybn** [breezy-weather/breezy-weather#1320]
### Steps to reproduce

1. Build the application from the main branch
2. Find a place where it is raining
3. The application crashed
```
FATAL EXCEPTION: main
Process: org.breezyweather, PID: 15351
java.lang.OutOfMemoryError: Failed to allocate a 124606360 byte allocation with 100663296 free bytes and 110MB until OOM, target footprint 521796832, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3560)
	at java.util.Arrays.copyOf(Arrays.java:3529)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:490)
	at java.util.ArrayList.add(ArrayList.java:503)
	at com.patrykandpatrick.vico.compose.cartesian.e.invoke(SourceFile:1554)
	at androidx.compose.ui.draw.g.d(SourceFile:3)
	at androidx.compose.ui.node.T.c(SourceFile:52)
	at androidx.compose.ui.node.N0.y0(SourceFile:55)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.G.Q0(SourceFile:6)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.G.Q0(SourceFile:6)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.G.Q0(SourceFile:6)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.Q.j(SourceFile:7)
	at androidx.compose.ui.node.B.Q0(SourceFile:28)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.G.Q0(SourceFile:6)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.G.Q0(SourceFile:6)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.G0.invoke(SourceFile:3)
	at androidx.compose.ui.node.G0.invoke(SourceFile:1)
	at androidx.compose.runtime.snapshots.z.e(SourceFile:114)
	at androidx.compose.runtime.snapshots.A.a(SourceFile:52)
	at androidx.compose.runtime.snapshots.E.d(SourceFile:131)
	at androidx.compose.ui.node.h1.a(SourceFile:3)
	at androidx.compose.ui.node.H0.invoke(SourceFile:8)
	at androidx.compose.ui.node.H0.invoke(SourceFile:1)
	at androidx.compose.ui.platform.N1.invoke(SourceFile:7)
	at androidx.compose.ui.platform.N1.invoke(SourceFile:1)
	at H.i.M(SourceFile:35)
	at H.c.e(SourceFile:55)
	at androidx.compose.ui.platform.O1.i(SourceFile:136)
	at androidx.compose.ui.platform.O1.e(SourceFile:25)
	at androidx.compose.ui.node.N0.w0(SourceFile:5)
	at androidx.compose.ui.node.Q.j(SourceFile:7)
	at androidx.compose.ui.node.B.Q0(SourceFile:28)
	at androidx.compose.ui.node.N0.y0(SourceFile:9)
	at androidx.compose.ui.node.N0.w0(SourceFile:28)
	at androidx.compose.ui.node.Q.j(SourceFile:7)
	at androidx.compose.ui.platform.N.dispatchDraw(SourceFile:67)
	at android.view.View.draw(View.java:24630)
	at android.view.View.updateDisplayListIfDirty(View.java:23493)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.View.draw(View.java:24357)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4576)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4337)
	at android.view.View.draw(View.java:24630)
	at android.view.View.updateDisplayListIfDirty(View.java:23493)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4533)
	at android.view.View.updateDisplayListIfDirty(View.java:23449)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4560)
```

### Expected behavior

Do not crash

### Actual behavior

crashed

### Weather source used

China

### Breezy Weather version

build from main branch `e1bb8713e04ccab1de18a9e7da14961a2fdd95cd`

### Android version

Android 14

### Device

Oneplus 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Probably the update of the Vico dependency; I can reproduce a freezing on my side when nowcasting chart is there

**Comment by min7-i** [comment]
This is caused by a bug introduced in the latest version of vico. There is already an issue for this [here](https://github.com/patrykandpatrick/vico/issues/890).
