### ISSUE TITLE
Crash on devices with no widget support

### ISSUE THREAD

**Issue by gaussandhisgun** [breezy-weather/breezy-weather#1344]
### Steps to reproduce

Buckle up, this is a weird one.

Step 1: sideload the app on a device that does not have any kind of "normal android" widget support. I'm using a Samsung Galaxy Watch 4 for this.
Step 2: go through the initial setup, pick a city and sources, etc etc.
Step 3: open the app.

### Expected behavior

App should load the info and just work

### Actual behavior

App immediately crashes

### Weather source used

Irrelevant

### Breezy Weather version

5.2.8

### Android version

Android 13; WearOS 4; OneUI 5.0 Watch

### Device

Samsung Galaxy Watch 4

### Other details

Log:

```
10-03 19:07:15.200 13558 13633 W SystemServiceRegistry: No service published for: appwidget
10-03 19:07:15.366 13558 13633 W System.err: F2.e: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
10-03 19:07:15.367 13558 13633 W System.err: 	at E5.f.b(SourceFile:5)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.observers.c.onError(SourceFile:14)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.operators.observable.d.onError(SourceFile:14)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.operators.observable.d.onComplete(SourceFile:24)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.operators.observable.l.checkTerminated(SourceFile:61)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.operators.observable.l.drainNormal(SourceFile:31)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.operators.observable.l.run(SourceFile:9)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.schedulers.p.run(SourceFile:14)
10-03 19:07:15.367 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.schedulers.p.call(SourceFile:1)
10-03 19:07:15.367 13558 13633 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-03 19:07:15.367 13558 13633 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-03 19:07:15.367 13558 13633 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-03 19:07:15.367 13558 13633 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-03 19:07:15.368 13558 13633 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
10-03 19:07:15.368 13558 13633 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
10-03 19:07:15.368 13558 13633 W System.err: 	at org.breezyweather.background.receiver.widget.a.g(SourceFile:6)
10-03 19:07:15.368 13558 13633 W System.err: 	at org.breezyweather.sources.i.n(SourceFile:19)
10-03 19:07:15.368 13558 13633 W System.err: 	at I0.m.run(SourceFile:113)
10-03 19:07:15.368 13558 13633 W System.err: 	at C0.d.run(SourceFile:10)
10-03 19:07:15.368 13558 13633 W System.err: 	at io.reactivex.rxjava3.internal.operators.observable.d.onComplete(SourceFile:8)
10-03 19:07:15.368 13558 13633 W System.err: 	... 10 more
10-03 19:07:15.369 13558 13633 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
10-03 19:07:15.369 13558 13633 E AndroidRuntime: Process: org.breezyweather, PID: 13558
10-03 19:07:15.369 13558 13633 E AndroidRuntime: F2.e: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at E5.f.b(SourceFile:5)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.observers.c.onError(SourceFile:14)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.d.onError(SourceFile:14)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.d.onComplete(SourceFile:24)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.l.checkTerminated(SourceFile:61)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.l.drainNormal(SourceFile:31)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.l.run(SourceFile:9)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.p.run(SourceFile:14)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.p.call(SourceFile:1)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at org.breezyweather.background.receiver.widget.a.g(SourceFile:6)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at org.breezyweather.sources.i.n(SourceFile:19)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at I0.m.run(SourceFile:113)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at C0.d.run(SourceFile:10)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.observable.d.onComplete(SourceFile:8)
10-03 19:07:15.369 13558 13633 E AndroidRuntime: 	... 10 more
```

This crash can be avoided. I already have at least one app on my watch, KDE Connect, that has widgets and does not immediately crash when trying to update them. Maybe checking if the `appwidget` service exists before updating widgets for edge cases like this will be a good idea?

(or you could make a dedicated watch-sized app - theres a noticeable lack of those for Wear OS, especially open source - but that takes a lot of time and effort)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
As written in Android documentation, APK compiled for Android mobile are different from APK compiled for Wear OS. There can't be one single APK working for both of them, that's why you had to sideload it, ignoring warnings. That was made on purpose by Google, because apps for watches have a very different design and interaction, so you actually make two different apps.

As you guessed it, because it's time-consuming, we have no intention to publish a separate WearOS app, make its own design, and maintaining it (fixing watches-specific bugs, etc).

You can submit a PR to fix the issue you're encountering (I believe it happens at the end of the refresh process, when trying to query installed widgets and update their weather data), but you will quickly see that you will hit a wall when trying to interact with the app (as per a few tests I made with an emulator a while ago), because it needs its own sized UI.

**Comment by gaussandhisgun** [comment]
> that's why you had to sideload it, ignoring warnings
(there were no warnings)

well, thanks for the explanation!
