### ISSUE TITLE
App crashes when I select met Norway

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#295]
### Steps to reproduce

I let it find my location.
Then I wanted to try different weather sources.
Then I switched to Met Norway as a test and it crashed immediately.

### Expected behavior

The app should open normally, the app should just start and not crash.

### Actual behavior

It crashes. It does not open.

### Weather source used

Met Norway

### Breezy Weather version

4.4.1-bata

### Android version

Android 13 and Android 12

### Device

Pixel 7 and Android Galaxy A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Please share with us your crash log.

You can do that from command line if you have access to `adb` on a PC:
`adb logcat --pid=$(adb shell pidof -s org.breezyweather)`

Or you can install an app that can help you do that, such as this one:
https://play.google.com/store/apps/details?id=com.dp.logcatapp

**Comment by papjul** [comment]
Please also provide more steps to reproduce, you say “I select met norway", what did you do exactly? Is it current location or is it a manually added location?

**Comment by ayntk-ai** [comment]
When I try to run ADB, this message appears:
```
.\adb logcat --pid=($(.\adb shell pidof -s org.breezyweather))
logcat: pid  out of range.
```

**Comment by papjul** [comment]
Can you try instead:
`adb logcat`

and open app after that and copy/paste lines related to Breezy Weather?

**Comment by ayntk-ai** [comment]
This is the output:
```
FATAL EXCEPTION: main
Process: org.breezyweather, PID: 5507
java.lang.RuntimeException: Unable to start receiver org.breezyweather.background.receiver.widget.WidgetClockDayVerticalProvider: java.lang.IllegalArgumentException: text cannot be null
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4770)
	at android.app.ActivityThread.access$1700(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: text cannot be null
	at android.graphics.Paint.measureText(Paint.java:2369)
	at org.breezyweather.remoteviews.g.a(SourceFile:127)
	at k8.m.m0(SourceFile:6)
	at org.breezyweather.remoteviews.g.d(SourceFile:56)
	at org.breezyweather.remoteviews.g.b(Unknown Source:85)
	at org.breezyweather.background.receiver.widget.AbstractWidgetProvider.onUpdate(Unknown Source:18)
	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4761)
	... 9 more
```

**Comment by papjul** [comment]
Thank you, I will fix it.
In the meantime, remove the widget and you will be able to open the app again.

**Comment by ayntk-ai** [comment]
I removed all the widgets, so the widget problem is there, but I think there is another problem because the app still crashes.
Logs:
```
FATAL EXCEPTION: RxCachedThreadScheduler-3
Process: org.breezyweather, PID: 23949
b5.e: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: text cannot be null
	at e5.a.a(SourceFile:12)
	at io.reactivex.rxjava3.internal.observers.c.onError(Unknown Source:13)
	at io.reactivex.rxjava3.internal.operators.observable.e.onError(Unknown Source:37)
	at io.reactivex.rxjava3.internal.operators.observable.e.onComplete(Unknown Source:36)
	at io.reactivex.rxjava3.internal.operators.observable.n.checkTerminated(Unknown Source:60)
	at io.reactivex.rxjava3.internal.operators.observable.n.drainNormal(Unknown Source:30)
	at io.reactivex.rxjava3.internal.operators.observable.n.run(Unknown Source:8)
	at io.reactivex.rxjava3.internal.schedulers.y.run(Unknown Source:13)
	at io.reactivex.rxjava3.internal.schedulers.y.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalArgumentException: text cannot be null
	at android.graphics.Paint.measureText(Paint.java:2369)
	at org.breezyweather.remoteviews.g.a(SourceFile:127)
	at k8.h.m0(SourceFile:7)
	at org.breezyweather.remoteviews.g.d(SourceFile:316)
	at d.p0.run(SourceFile:164)
	at v7.b.run(SourceFile:21)
	at io.reactivex.rxjava3.internal.operators.observable.e.onComplete(Unknown Source:7)
	... 10 more
```
```
win=Window{fa9cc7b u0 Splash Screen org.breezyweather EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5867 com.android.server.wm.ActivityRecord.destroySurfaces:5848 com.android.server.wm.WindowState.onExitAnimationDone:5982 com.android.server.wm.WindowStateAnimator.onAnimationFinished:242 com.android.server.wm.WindowState.onAnimationFinished:6235 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda0.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:113 
```
```
An exception occurred : 
java.util.concurrent.ExecutionException: android.content.res.Resources$NotFoundException: Drawable org.breezyweather:mipmap/ic_launcher with resource ID #0x7f100000
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at android.content.res.Resources.fetchDrawableFromFutureCache(Resources.java:2751)
	at android.content.res.Resources.loadDrawable(Resources.java:1064)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:1048)
	at android.content.res.Resources.getDrawable(Resources.java:987)
	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1740)
	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3601)
	at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:3498)
	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:318)
	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:313)
	at v8.c.<init>(SourceFile:30)
	at kotlin.jvm.internal.j.Q0(SourceFile:9)
	at kotlin.jvm.internal.j.P0(Unknown Source:14)
	at org.breezyweather.main.fragments.HomeFragment.L(Unknown Source:26)
	at org.breezyweather.main.fragments.HomeFragment.t(SourceFile:196)
	at androidx.fragment.app.x.F(SourceFile:20)
	at androidx.fragment.app.a1.f(SourceFile:200)
	at androidx.fragment.app.a1.k(SourceFile:118)
	at androidx.fragment.app.s0.K(SourceFile:62)
	at androidx.fragment.app.s0.t(SourceFile:36)
	at androidx.fragment.app.a0.onStart(SourceFile:35)
	at androidx.appcompat.app.a.onStart(SourceFile:1)
	at org.breezyweather.main.MainActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.content.res.Resources$NotFoundException: Drawable org.breezyweather:mipmap/ic_launcher with resource ID #0x7f100000
Caused by: android.content.res.Resources$NotFoundException: File res/uF.xml from drawable resource ID #0x7f100000
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:1039)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:825)
	at android.content.res.Resources$submitToFuture.call(Resources.java:2856)
	at android.content.res.Resources$submitToFuture.call(Resources.java:2838)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Application.getResources()' on a null object reference
	at android.graphics.drawable.AdaptiveIconDrawable.<init>(AdaptiveIconDrawable.java:165)
	at android.graphics.drawable.AdaptiveIconDrawable.<init>(AdaptiveIconDrawable.java:152)
```
```
[Splash Screen org.breezyweather$_1678#0](this:0xb40000794d7a0948,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Splash Screen org.breezyweather$_1678#0'
```
```
An exception occurred : 
java.util.concurrent.ExecutionException: android.content.res.Resources$NotFoundException: Drawable org.breezyweather:mipmap/ic_launcher with resource ID #0x7f100000
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at android.content.res.Resources.fetchDrawableFromFutureCache(Resources.java:2751)
	at android.content.res.Resources.loadDrawable(Resources.java:1064)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:1048)
	at android.content.res.Resources.getDrawable(Resources.java:987)
	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1740)
	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3601)
	at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:3498)
	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:318)
	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:313)
	at v8.c.<init>(SourceFile:30)
	at kotlin.jvm.internal.j.Q0(SourceFile:9)
	at kotlin.jvm.internal.j.P0(Unknown Source:14)
	at org.breezyweather.main.fragments.HomeFragment.L(Unknown Source:26)
	at org.breezyweather.main.fragments.HomeFragment.t(SourceFile:196)
	at androidx.fragment.app.x.F(SourceFile:20)
	at androidx.fragment.app.a1.f(SourceFile:200)
	at androidx.fragment.app.a1.k(SourceFile:118)
	at androidx.fragment.app.s0.K(SourceFile:62)
	at androidx.fragment.app.s0.t(SourceFile:36)
	at androidx.fragment.app.a0.onStart(SourceFile:35)
	at androidx.appcompat.app.a.onStart(SourceFile:1)
	at org.breezyweather.main.MainActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.content.res.Resources$NotFoundException: Drawable org.breezyweather:mipmap/ic_launcher with resource ID #0x7f100000
Caused by: android.content.res.Resources$NotFoundException: File res/uF.xml from drawable resource ID #0x7f100000
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:1039)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:825)
	at android.content.res.Resources$submitToFuture.call(Resources.java:2856)
	at android.content.res.Resources$submitToFuture.call(Resources.java:2838)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Application.getResources()' on a null object reference
	at android.graphics.drawable.AdaptiveIconDrawable.<init>(AdaptiveIconDrawable.java:165)
	at android.graphics.drawable.AdaptiveIconDrawable.<init>(AdaptiveIconDrawable.java:152)
```

**Comment by papjul** [comment]
The first crash is still the widget error. Other are mentioning a missing resource that is part of the APK, so it’s probably a false positive, unless your storage is corrupted. I would full restart the device, or if it doesn’t help, wait for v4.5.1.

**Comment by ayntk-ai** [comment]
Everything seems to be working perfectly now, thank you for your great work and bringing this great Weather app back to life.
