### ISSUE TITLE
Crash with AccuWeather

### ISSUE THREAD

**Issue by Mylloon** [breezy-weather/breezy-weather#362]
### Steps to reproduce

1. Use AccuWeather, in my case its a secondary source

### Expected behavior

It should work

### Actual behavior

It actually crashed

### Weather source used

AccuWeather

### Breezy Weather version

4.5.4-beta

### Android version

Android 12

### Device

Mi Note 10 Lite

### Other details

The crash happen with all location I tried

<details><summary>Here is the log when I open the app with Accuweather as a secondary source</summary>

```
FATAL EXCEPTION: main
Process: org.breezyweather, PID: 6583
java.lang.NullPointerException
    at org.breezyweather.main.adapters.main.n.g(SourceFile:697)
    at androidx.recyclerview.widget.v0.h(Unknown Source:0)
    at androidx.recyclerview.widget.n1.l(SourceFile:1335)
    at androidx.recyclerview.widget.n1.d(Unknown Source:5)
    at org.breezyweather.main.layouts.MainLayoutManager.h0(SourceFile:70)
    at androidx.recyclerview.widget.RecyclerView.t(SourceFile:87)
    at androidx.recyclerview.widget.RecyclerView.r(SourceFile:113)
    at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at i2.l.onLayout(Unknown Source:58)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.p(SourceFile:403)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.p(SourceFile:403)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:866)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3866)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3316)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2280)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9026)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1144)
at android.view.Choreographer.doCallbacks(Choreographer.java:948)
    at android.view.Choreographer.doFrame(Choreographer.java:877)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8337)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```
</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Did you put AccuWeather as your alert source and no precipitation source? In that case, I noticed an issue indeed that will be fixed in next version.

**Comment by papjul** [comment]
Indeed, it seems to be that way, it happens in the same file, although I cannot seem to get the correct line crashing on the decoded stacktrace.

Decoded stacktrace:
```
FATAL EXCEPTION: main
Process: org.breezyweather, PID: 6583
java.lang.NullPointerException
    at org.breezyweather.main.adapters.main.MainAdapter.org.breezyweather.main.adapters.main.holder.FooterViewHolder.onBindView(SourceFile:697)
                                                        onBindViewHolder
                                                        onBindViewHolder
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(Unknown Source:0)
    at androidx.recyclerview.widget.RecyclerView$Recycler.androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:1335)
                                                          tryBindViewHolderByDeadline
                                                          tryGetViewHolderForPositionByDeadline
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5)
                                                          getViewForPosition
    at org.breezyweather.main.layouts.MainLayoutManager.onLayoutChildren(SourceFile:70)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:87)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:113)
    at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(SourceFile:403)
                                                           onLayoutChild
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(SourceFile:403)
                                                           onLayoutChild
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:866)
    at android.view.View.layout(View.java:23568)
    at android.view.ViewGroup.layout(ViewGroup.java:6452)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3866)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3316)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2280)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9026)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1144)
at android.view.Choreographer.doCallbacks(Choreographer.java:948)
    at android.view.Choreographer.doFrame(Choreographer.java:877)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1129)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8337)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037) 
```
