### ISSUE TITLE
Crash when losting network connection while adding the very first location

### ISSUE THREAD

**Issue by Penaz91** [breezy-weather/breezy-weather#478]
### Steps to reproduce

1. Enable your network
2. Search for a new location to add to the location list
3. Before selecting the location, disable all networks (to simulate a temporary outage)
4. Select a location to add

### Expected behavior

Either the location is added but no weather updates are found or a "Cannot add location" warning is shown

### Actual behavior

App crashes and closes down

### Weather source used

OpenMeteo

### Breezy Weather version

4.6.7-beta

### Android version

Android 10

### Device

Xiaomi RedMi Note 7

### Other details

I managed to catch the traceback:

```
33479:09-20 08:07:59.651 13087 13087 W System.err: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
33480:09-20 08:07:59.657 13087 13087 W System.err: 	at java.util.ArrayList.get(ArrayList.java:437)
33481:09-20 08:07:59.657 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.updateInnerData(MainActivityViewModel.kt:168)
33482:09-20 08:07:59.657 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.updateInnerData(MainActivityViewModel.kt:134)
33483:09-20 08:07:59.657 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.onUpdateResult(MainActivityViewModel.kt:197)
33484:09-20 08:07:59.657 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.onCompleted(MainActivityViewModel.kt:456)
33485:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityRepository.getWeather(MainActivityRepository.kt:105)
33486:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel$updateWithUpdatingChecking$3.invokeSuspend(MainActivityViewModel.kt:280)
33487:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
33488:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
33489:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
33490:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
33491:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
33492:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
33493:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
33494:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
33495:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
33496:09-20 08:07:59.658 13087 13087 W System.err: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
33497:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.updateWithUpdatingChecking(MainActivityViewModel.kt:279)
33498:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.checkToUpdateCurrentLocation(MainActivityViewModel.kt:219)
33499:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.setCurrentLocation(MainActivityViewModel.kt:184)
33500:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.updateInnerData(MainActivityViewModel.kt:168)
33501:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivityViewModel.addLocation(MainActivityViewModel.kt:389)
33502:09-20 08:07:59.658 13087 13087 W System.err: 	at org.breezyweather.main.MainActivity.onActivityResult(MainActivity.kt:183)
33503:09-20 08:07:59.658 13087 13087 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
33504:09-20 08:07:59.658 13087 13087 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
33505:09-20 08:07:59.658 13087 13087 W System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
33506:09-20 08:07:59.658 13087 13087 W System.err: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
33507:09-20 08:07:59.658 13087 13087 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
33508:09-20 08:07:59.658 13087 13087 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
33509:09-20 08:07:59.659 13087 13087 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
33510:09-20 08:07:59.659 13087 13087 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
33511:09-20 08:07:59.659 13087 13087 W System.err: 	at android.os.Looper.loop(Looper.java:224)
33512:09-20 08:07:59.659 13087 13087 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7590)
33513:09-20 08:07:59.659 13087 13087 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
33514:09-20 08:07:59.659 13087 13087 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
33515:09-20 08:07:59.659 13087 13087 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> Either the location is added but no weather updates are found or a "Cannot add location" warning is shown

Which is normal? If you don't have network, how do you expect to have a weather update?
The message is "Network unavailable", we don't have "Cannot add location".

I'm unable to get a crash with your step-by-step.

**Comment by Penaz91** [comment]
Could this be due to AdAway VPN again?

I'm under the impression that it's somehow falsifying the connection status for other applications.

**Comment by papjul** [comment]
App correctly reports "Network unavailable" warning if I redo your steps with a VPN enabled with no other networks.

Please share a video.

**Comment by Penaz91** [comment]
Sure thing:

https://github.com/breezy-weather/breezy-weather/assets/6682630/bf500d15-77a3-4e2b-8510-ed88a4d6ef41

I may have hit a corner case where this happens only on first install or after a complete data wipe of the app (the only moments I can imagine the location list can be empty, since you can't delete the last location saved)

**Comment by papjul** [comment]
Has a workaround:
- Reopen the app
- Add the location again once your network is stable

**Comment by ecawthorne** [comment]
I was able to reproduce this on both an emulated and physical device. It seems like it was fixed in 91eedf1e so this issue can probably be closed at this point.

**Comment by papjul** [comment]
@Penaz91 Please confirm if you still experience issues, or close the issue. Thanks!

**Comment by Penaz91** [comment]
I just verified with the latest version. The new position gets added but a "no network available" message is shown, as expected.
Thank you for fixing this!
