### ISSUE TITLE
Crash when adding too much data to the header on v5.0.0

### ISSUE THREAD

**Issue by Yaya-Cout** [breezy-weather/breezy-weather#710]
### Steps to reproduce

1. Add a location
2. Add many data to the header
3. See crash

### Expected behavior

The application should not crash

### Actual behavior

The application crash

### Weather source used

Meteo France

### Breezy Weather version

v5.0.0-alpha

### Android version

Android 14 (on GrapheneOS)

### Device

Pixel 6a

### Other details

I have no Google Play Services installed, but I don't think it's relevant.
Error message :
```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.240205.002/2024022300:user/release-keys
package: org.breezyweather:50000
process: org.breezyweather
processUptime: 3127 + 350 ms
installer: dev.imranr.obtainium

java.lang.IndexOutOfBoundsException: toIndex = 6
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.util.ArrayList.subList(ArrayList.java:1125)
	at androidx.compose.ui.node.g2.a(SourceFile:1)
	at org.breezyweather.main.adapters.main.o.q(SourceFile:204)
	at org.breezyweather.main.fragments.HomeFragment.R(SourceFile:185)
	at org.breezyweather.main.fragments.j.emit(SourceFile:198)
	at kotlinx.coroutines.flow.w0.a(SourceFile:199)
	at kotlinx.coroutines.flow.v0.invokeSuspend(Unknown Source:12)
	at z5.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.j0.v(SourceFile:1)
	at kotlinx.coroutines.k.p(SourceFile:76)
	at kotlinx.coroutines.k.B(SourceFile:33)
	at kotlinx.coroutines.k.resumeWith(SourceFile:17)
	at kotlinx.coroutines.flow.w0.k(SourceFile:104)
	at kotlinx.coroutines.flow.w0.j(SourceFile:1)
	at org.breezyweather.main.u.invokeSuspend(SourceFile:122)
	at z5.a.resumeWith(SourceFile:9)
	at kotlinx.coroutines.q0.run(Unknown Source:98)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: kotlinx.coroutines.internal.g: [b2{Cancelling}@b721fc1, Dispatchers.Main.immediate]
``` 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Fixed by 9ccb5d804805924591449c5ae65e29909eaad22e, hot fix release in a few minutes
